# Uniform dataset, training parameters.

params_ae = {
    'ae_class': 'Autoencoder',
    'train_class': 'train_ae',
    'dataset_class': 'MinigridMemoryUniformDataset',
    'log_name': 'minigrid_uniform_memory_ae',
    'latent_dims': 256,
    'input_dims': 48,
    'hidden_size': 16,
    'batch_size': 2048,
    'epochs': 500,
    'train_set_ratio': 0.8,
    'in_channels': 3,
    'learning_rate': 1e-5,
    'maximum_gradient': 1e7,
    'kernel_size': 7,
    'padding': 0,
    'dilation': 1,
    'conv_hidden_size': 32,
    'conv1_stride': 1,
    'maxpool_stride': 1,
    'lambda': 0.1,
}

params_vae = {
    'ae_class': 'VariationalAutoencoder',
    'train_class': 'train_vae',
    'dataset_class': 'MinigridMemoryUniformDataset',
    'log_name': 'minigrid_uniform_memory_vae',
    'latent_dims': 256,
    'input_dims': 48,
    'hidden_size': 16,
    'batch_size': 2048,
    'epochs': 500,
    'train_set_ratio': 0.8,
    'in_channels': 3,
    'learning_rate': 1e-5,
    'maximum_gradient': 1e7,
    'kernel_size': 7,
    'padding': 0,
    'dilation': 1,
    'conv_hidden_size': 32,
    'conv1_stride': 1,
    'maxpool_stride': 1,
    'lambda': 0.1,
}


params_conv_ae = {
    'ae_class': 'ConvAutoencoder',
    'train_class': 'train_ae',
    'dataset_class': 'MinigridMemoryUniformDataset',
    'log_name': 'minigrid_uniform_memory_conv_ae',
    'latent_dims': 256,
    'input_dims': 48,
    'hidden_size': 16,
    'batch_size': 2048,
    'epochs': 500,
    'train_set_ratio': 0.8,
    'in_channels': 3,
    'learning_rate': 1e-5,
    'maximum_gradient': 1e7,
    'kernel_size': 7,
    'padding': 0,
    'dilation': 1,
    'conv_hidden_size': 32,
    'conv1_stride': 1,
    'maxpool_stride': 1,
    'lambda': 0.1,
}

params_conv_vae = {
    'ae_class': 'ConvVariationalAutoencoder',
    'train_class': 'train_vae',
    'dataset_class': 'MinigridMemoryUniformDataset',
    'log_name': 'minigrid_uniform_memory_conv_vae',
    'latent_dims': 256,
    'input_dims': 48,
    'hidden_size': 16,
    'batch_size': 2048,
    'epochs': 500,
    'train_set_ratio': 0.8,
    'in_channels': 3,
    'learning_rate': 1e-5,
    'maximum_gradient': 1e7,
    'kernel_size': 7,
    'padding': 0,
    'dilation': 1,
    'conv_hidden_size': 32,
    'conv1_stride': 1,
    'maxpool_stride': 1,
    'lambda': 0.1,
}

params_conv_binary_ae = {
    'ae_class': 'ConvBinaryAutoencoder',
    'train_class': 'train_ae_binary',
    'dataset_class': 'MinigridMemoryUniformDataset',
    'log_name': 'minigrid_uniform_memory_conv_binary_ae',
    'latent_dims': 256,
    'input_dims': 48,
    'hidden_size': 16,
    'batch_size': 2048,
    'epochs': 500,
    'train_set_ratio': 0.8,
    'in_channels': 3,
    'learning_rate': 1e-5,
    'maximum_gradient': 1e7,
    'kernel_size': 7,
    'padding': 0,
    'dilation': 1,
    'conv_hidden_size': 32,
    'conv1_stride': 1,
    'maxpool_stride': 1,
    'lambda': 0.1,
}

params_list = [
    params_ae, params_vae,
    params_conv_ae, params_conv_vae]
